version: 2
executorType: docker
containerInfo:
  - image: unasuke/ruby-nodejs:2.3.4-nodejs6
stages:
  build: 
    workDir: ~/blog
    steps:
      - checkout
      - type: shell
        name: Install npm packages
        command: yarn install
      - type: shell
        name: Install gems
        command: bundle install
      - type: shell
        name: build blog
        command: bundle exec middleman build
