version: 2
executorType: docker
containerInfo:
  - image: unasuke/ruby-nodejs:2.4.1-nodejs8
stages:
  build: 
    workDir: ~/blog
    steps:
      - checkout
      - restore_cache:
          keys:
            - gems
            - node_modules
            - builded_pages
      - run: apt update && apt install --assume-yes rsync
      - run:
          command: npm install
      - save_cache:
          key: node_modules
          paths:
            - node_modules
      - run:
          command: bundle install --path vendor/bundle
      - save_cache:
          key: gems
          paths:
            - vendor/bundle
      - run:
          command: bundle exec middleman build
      - save_cache:
          key: builded_pages
          paths:
            - build
      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bundle exec middleman s3_sync
            fi
