on:
  push:
    branches:
      - 'master'
jobs:
  s3_sync:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update && sudo apt-get install -y libvips-dev
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: arn:aws:iam::423695832787:role/static-site-deploy-role
          aws-region: ap-northeast-1
      - uses: ruby/setup-ruby@0cb964fd540e0a24c900370abf38a33466142735 # v1.305.0
        with:
          bundler-cache: true
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: npm
      - run: npm ci
      - run: bundle exec middleman build
      - run: aws s3 sync ./build s3://static-site-blog-unasuke-com --delete --quiet
      - run: aws cloudfront create-invalidation --distribution-id E27VRKNRHRNYHG --paths "/*"
