on:
  push:
    branches:
      - 'master'
jobs:
  s3_sync:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update && sudo apt-get install -y libvips-dev
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: arn:aws:iam::423695832787:role/static-site-deploy-role
          aws-region: ap-northeast-1
      - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          bundler-cache: true
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: npm
      - run: npm ci
      - run: bundle exec middleman build
      - run: aws s3 sync ./build s3://static-site-blog-unasuke-com --delete --quiet
      - run: aws cloudfront create-invalidation --distribution-id E27VRKNRHRNYHG --paths "/*"
